steps:
  - name: "node:10.16.3"
    id: root-install
    entrypoint: npm
    args: ["install"]

  # create-service-provider: dependency installation
  - name: "node:10.16.3"
    id: create-service-provider-install
    waitFor:
      - root-install
    entrypoint: npm
    args: ["install"]
    dir: src/services/create-service-provider

  # configuration-service: dependency installation
  - name: "node:10.16.3"
    id: configuration-service-install
    waitFor:
      - root-install
    entrypoint: npm
    args: ["install"]
    dir: src/services/configuration-service

  # Validate build
  - name: "node:10.16.3"
    id: lint
    entrypoint: npm
    args: ["run", "lint"]

  - name: "node:10.16.3"
    id: test-unit
    entrypoint: npm
    args: ["run", "test"]

  # create-service-provider: Build docker image
  - name: "gcr.io/cloud-builders/docker"
    id: build-create-service-provider
    waitFor:
      - test-unit
    args:
      - build
      - --build-arg
      - service=create-service-provider
      - -t
      - gcr.io/sweng-581-capstone/create-service-provider:0.0.1
      - .

  # create-service-provider: Push docker image
  - name: "gcr.io/cloud-builders/docker"
    id: push-create-service-provider
    waitFor:
      - build-create-service-provider
    args: ["push", "gcr.io/sweng-581-capstone/create-service-provider:0.0.1"]

  # configuration-service: Build docker image
  - name: "gcr.io/cloud-builders/docker"
    id: build-configuration-service
    waitFor:
      - test-unit
    args:
      - build
      - --build-arg
      - service=configuration-service
      - -t
      - gcr.io/sweng-581-capstone/service-provider-config-service:0.0.1
      - .

  # configuration-service: Push docker image
  - name: "gcr.io/cloud-builders/docker"
    id: push-configuration-service
    waitFor:
      - build-configuration-service
    args:
      [
        "push",
        "gcr.io/sweng-581-capstone/service-provider-config-service:0.0.1",
      ]

  # create-service-provider: Deploy to cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - push-create-service-provider
    args:
      - beta
      - run
      - deploy
      - create-service-provider
      - --image=gcr.io/sweng-581-capstone/create-service-provider:0.0.1
      - --region=us-central1
      - --platform=managed

  # configuration-service: Deploy to cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - push-configuration-service
    args:
      - beta
      - run
      - deploy
      - service-provider-config-service
      - --image=gcr.io/sweng-581-capstone/service-provider-config-service:0.0.1
      - --region=us-central1
      - --platform=managed
images:
  - "gcr.io/sweng-581-capstone/create-service-provider"
  - "gcr.io/sweng-581-capstone/service-provider-config-service:0.0.1"
