steps:
  - name: "node:10.16.3"
    id: root-install
    entrypoint: npm
    args: ["install"]
  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-configuration-service
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/configuration-service/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-create-service-offering
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/create-service-offering/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-create-service-provider
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/create-service-provider/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-delete-service-provider
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/delete-service-provider/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-offering-notification-processor
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/offering-notification-processor/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-provider-delete-notification-processor
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/provider-delete-notification-processor/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-provider-search
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/provider-search/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-query-service-provider
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/query-service-provider/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-staff-membership-accepted-notification-processor
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/staff-membership-accepted-notification-processor/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-staff-membership-request
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/staff-membership-request/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-staff-membership-request-query
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/staff-membership-request-query/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-staff-membership-request-update
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/staff-membership-request-update/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-update-service-offering
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/update-service-offering/cloudbuild.yaml
      wait

  - name: 'gcr.io/cloud-builders/gcloud'
    id: fork-build-update-service-provider
    entrypoint: 'bash'
    waitFor:
      - root-install
    args:
    - '-c'
    - |
      gcloud builds submit $d --config=./src/services/update-service-provider/cloudbuild.yaml
      wait