steps:
  - name: "node:10.16.3"
    id: root-install
    entrypoint: npm
    args: ["install"]

  - name: "node:10.16.3"
    id: lint
    entrypoint: npm
    args: ["run", "lint"]

  - name: "node:10.16.3"
    id: test-unit
    entrypoint: npm
    args: ["run", "test"]
