npm install
cd ./src/services/configuration-service
npm install
cd ../create-service-offering
npm install
cd ../create-service-provider
npm install
cd ../delete-service-provider
npm install
cd ../offering-notification-processor
npm install
cd ../provider-delete-notification-processor
npm install
cd ../provider-search
npm install
cd ../query-service-provider
npm install
cd ../staff-membership-approved-notification-processor
npm install
cd ../staff-membership-request
npm install
cd ../staff-membership-request-query
npm install
cd ../staff-membership-request-update
npm install
cd ../update-service-offering
npm install
cd ../update-service-proider
npm install